#!/bin/sh

# archlinux

notas="
libicudata.so.76       icu76                                    Chinese Community x86_64
libfltk.so.1.3.8       lib64fltk1.3-1.3.8-2-omv4090.x86_64.rpm  OpenMandriva Main Release x86_64
"

tabla="
xset                   xorg-xset
mount                  util-linux
xhost                  xorg-xhost
e2fsck                 e2fsprogs
libxml2.so.2           libxml2-legacy
libmount.so.1          util-linux-libs
libdbus-1.so.3         dbus
libcrypto.so.3         openssl
libassimp.so.6         assimp
libicudata.so.76       icu76
libfltk.so.1.3.8       null
libIex-3_4.so.33       openexr
grub-mkdevicemap       null
libgphoto2.so.6.3.0    null
libOpenColorIO.so.2.5  opencolorio
part_msdos.mod         grub-2
dpkg-preconfigure      null
lvm                    lvm2
pdata_tools            thin-provisioning-tools
mount.cifs             cifs-utils
dpkg-preconfigure      null
"

echo "$tabla" | awk -v key="$1" '$1 == key { print $2 }'
