#!/bin/sh

export disco="n"
export iso="iso"
export fci="$disco/$iso"

# Cambiar de ruta al disco de montaje
cd "/$disco"

# Para evitar errores chase
sudo mount -o subvol=@ /dev/sda1 "/$disco"

# Desmontar sistema del disco
sudo umount "/$disco/"* 2>/dev/null

# Conecta afuera con adentro de chroot.
sudo mkdir -p "/$fci"
sudo mount --bind "/" "/$fci"

# Montar /dev
o="dev"
sudo mount --bind "/$o" "/$disco/$o"

# Montar /dev dentro del disco
sudo mount --bind "/$o" "/$fci/$o"

p="pts"
sudo mount --bind "/$o/$p" "/$disco/$o/$p"

# Montar proc sin bind (esto resuelve los errores de uuid y boot_id)
o="proc"
sudo mount --bind "/$o" "/$disco/$o"

# Montar sysfs
o="sys"
sudo mount -t "${o}fs" "/$o" "/$disco/$o"

# Forzar copia de entrar hacia afuera de chroot
sudo cp -vf "/$disco/local/bin/entrar" "/bin" 1>/dev/null

# Reparar systemd-cat
sudo mount --bind /run/systemd/journal /$disco/run/systemd/journal 2>/dev/null

# Copiar configuración del internet
sudo cp -vf "/$disco/etc/resolv.conf" "/etc" 1>/dev/null

# Copiar configuración del pacman
sudo cp -vf "/$disco/etc/pacman.conf" "/etc" 1>/dev/null

# Reparar pacman-mirrors
mkdir -pv /usr/lib/python3.14/site-packages 1>/dev/null
cp -vfr /usr/lib/python3.13/site-packages/pacman_mirrors /usr/lib/python3.14/site-packages 1>/dev/null

# Entrar
sudo chroot "/$disco" bash --login
