#!/bin/sh

# Para usar esto primero hacer lo siguiente y guardar este archivo.
# mv ldconfig ldconfig.real

# Ejecutamos el binario real, unificando salida de error y estándar
# Leemos la salida línea por línea
ldconfig.real "$@" 2>&1 | while IFS= read -r line; do
        # 1. Ignorar si la línea está vacía (solo espacios o nula)
        [[ $(echo "$line" | grep -Ei "^([[:space:]]|\t)+$" ) ]] && continue

        # 2. Ignorar si la línea contiene "libc.so" o "libc-"
        [[ "$line" == *"libc.so"* ]] || [[ "$line" == *"libc-"* ]] && continue

        # Si pasa los filtros, imprimimos la línea original
        echo "$line"
done

# Forzamos salida exitosa para que los procesos de pacman/mkinitcpio continúen
exit 0
