#!/bin/bash

# Para usar esto primero hacer lo siguiente y guardar este archivo.
# mv ldconfig ldconfig.real

# Iteramos sobre todos los argumentos pasados al comando
for arg in "$@"; do
        # Si el argumento contiene "libc.so" o "libc-2", saltamos la ejecución para ese caso
        if [[ "$arg" == *"libc.so"* ]] || [[ "$arg" == *"libc-"* ]]; then
                return 0
        fi
done

# Si no se detectó libc en los argumentos, ejecutamos el binario real
# Usamos "exec" para que el proceso real tome el lugar del script
exec ldconfig.real "$@"
