#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Uso: lw <nombre_del_ejecutable>"
    exit 1
fi

# Localiza el binario usando el PATH actual
target=$(which "$1" 2>/dev/null)

if [[ -f "$target" ]]; then
    ldd "$target"
else
    echo "Comando '$1' no encontrado."
    exit 1
fi
